# -*- coding: utf-8 -*-
"""cv lab3

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Dp2-yyW3jiGhea4wVeJGaQRNUkD3lYLs
"""

import cv2
from matplotlib import pyplot as plt
import numpy as np

#Function to display images
def show_comparison(original,blur3,blur5,blur7):
  plt.figure(figsize=(12,10))
  #Original image
  plt.subplot(2,2,1)
  plt.imshow(original,cmap='gray')
  plt.title("Original Grayscal Image")
  plt.axis('off')
#3*3 kernel
  plt.subplot(2,2,2)
  plt.imshow(blur3,cmap='gray')
  plt.title("Average Filter(3*3)")
  plt.axis('off')
  #5*5 kernel
  plt.subplot(2,2,3)
  plt.imshow(blur5,cmap='gray')
  plt.title("Average Filter(5*5)")
  plt.axis('off')
  #7*7 kernel
  plt.subplot(2,2,4)
  plt.imshow(blur7,cmap='gray')
  plt.title("Average Filter(7*7)")
  plt.axis('off')
  plt.show()

#read image 1 in grayscle
img =cv2.imread('/content/filter-coffee',0)
if img is None:
  print("Error: Image not found")
else:
  kernel_3x3==np.ones((3,3),np.float32)/9
  kernel_5x5==np.ones((5,5),np.float32)/25
  kernel_7x7==np.ones((7,7),np.float32)/49
  blur_3=cv2.filter2D(img,-1,kernel_3x3)
  blur_5=cv2.filter2D(img,-1,kernel_5x5)
  blur_7=cv2.filter2D(img,-1,kernel_7x7)
  show_comparison(img,blur_3,blur_5,blur_7)

import cv2
from matplotlib import pyplot as plt
import numpy as np
#read image 1 in grayscle
img =cv2.imread('/content/satrun',0)
if img is None:
  print("Error: Image not found")
else:
  kernel_3x3=np.ones((3,3),np.float32)/9
  kernel_5x5=np.ones((5,5),np.float32)/25
  kernel_7x7=np.ones((7,7),np.float32)/49
  blur_3=cv2.filter2D(img,-1,kernel_3x3)
  blur_5=cv2.filter2D(img,-1,kernel_5x5)
  blur_7=cv2.filter2D(img,-1,kernel_7x7)
  show_comparison(img,blur_3,blur_5,blur_7)

kernel = np.ones((3,3))*1/9
k_s=3;
Filtered_img=np.zeroes((0.5,0.5))
m=img1.shape[0]
m=img1.shape[1]
for i in range(m-k_s+1):
  for

